# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-18 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.TextField()),
                ('pic', models.ImageField(upload_to='')),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
                ('edit_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'advertises',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField()),
                ('comment_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200, verbose_name='国家/地区')),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='LeadRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='演员名称')),
            ],
            options={
                'db_table': 'leadroles',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='视频名称')),
                ('release_time', models.DateField(verbose_name='上映时间')),
                ('director', models.CharField(max_length=200, verbose_name='导演')),
                ('length', models.CharField(max_length=4, verbose_name='片长')),
                ('imdb_link', models.CharField(max_length=200, null=True, verbose_name='Imdb链接')),
                ('mark', models.FloatField(max_length=4, verbose_name='评分')),
                ('cover_link', models.ImageField(upload_to='', verbose_name='封面图片')),
                ('summary', models.TextField(verbose_name='剧情简介')),
                ('is_delete', models.BooleanField(default=0, verbose_name='是否删除')),
                ('is_carousel', models.BooleanField(default=0, verbose_name='是否首页轮播展示')),
                ('is_sidebar', models.BooleanField(default=0, verbose_name='侧边栏推荐展示')),
                ('is_vipfilm', models.IntegerField(default=0, verbose_name='是否是vip电影')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.Country', verbose_name='国家/地区')),
                ('lead_role', models.ManyToManyField(to='store.LeadRole', verbose_name='主演')),
            ],
            options={
                'db_table': 'movies',
            },
        ),
        migrations.CreateModel(
            name='StyleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_type', models.CharField(max_length=20, verbose_name='风格类型')),
            ],
            options={
                'db_table': 'styletypes',
            },
        ),
        migrations.CreateModel(
            name='Visited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.Movie')),
            ],
            options={
                'db_table': 'visited',
            },
        ),
        migrations.DeleteModel(
            name='Ad',
        ),
        migrations.RemoveField(
            model_name='caritem',
            name='clothing',
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='category',
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='size',
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='tag',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='qq',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='user',
            name='is_vip',
            field=models.IntegerField(default=0, verbose_name='vip用户'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribe',
            field=models.CharField(default='on', max_length=4, verbose_name='是否订阅电子杂志'),
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='user',
            name='v_end',
            field=models.DateField(default='2019-01-01'),
        ),
        migrations.AddField(
            model_name='user',
            name='v_start',
            field=models.DateField(default='2019-01-01'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=64, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=32, unique=True, verbose_name='昵称'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Caritem',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Clothing',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='visited',
            name='u',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.User'),
        ),
        migrations.AddField(
            model_name='movie',
            name='like',
            field=models.ManyToManyField(to='store.User', verbose_name='喜欢'),
        ),
        migrations.AddField(
            model_name='movie',
            name='style_type',
            field=models.ManyToManyField(to='store.StyleType', verbose_name='风格类型'),
        ),
        migrations.AddField(
            model_name='comment',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.Movie'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.User'),
        ),
    ]
