# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-18 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20190918_2013'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advertise',
        ),
    ]
